name: Executa Validatorul Java

on: [push]

jobs:
  run-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Seteaza Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compileaza si Ruleaza
        run: |
          # 1. Compilăm din folderul MAIN (acolo unde este logica programului)
          javac src/main/java/com/mihalachecatalin/homework/UsernameValidator.java
          
          # 2. Rulăm clasa folosind classpath-ul către folderul main
          echo -e "user cu spatiu\nscurt\nvalidUser123" | java -cp src/main/java com.mihalachecatalin.homework.UsernameValidator

