name: Executa Validatorul Java

on: [push]

jobs:
  run-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cod
        uses: actions/checkout@v4

      - name: Seteaza Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compileaza si Ruleaza
        run: |
          # 1. Compilam din folderul cu fisierul test
          javac src/test/java/com/catalinmihalache/homework/UsernameValidator.java
          
          # 2. Rulam folosind calea de test, dar numele de pachet corect
          # (mihalachecatalin)
          echo -e "user gresit\nvalid123" | java -cp src/test/java com.mihalachecatalin.homework.UsernameValidator


